apiVersion: v1
kind: Service
metadata:
   name: dbsvc
spec:
  type: ClusterIP
  selector:
    db: redis
  ports:
    - port: 6369       # Service Port using which we can access db inside cluster
      targetPort: 8080 # container Port inside pod
