apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: mypod  
      labels:
        app: web
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 8080
